bors-ng:
  adminRoles: []
  repos:
    - github.com/bors-ng/bors-ng:*
  workerPools:
    ci:
      owner: michael@notriddle.com
      emailOnError: false
      imageset: generic-worker-ubuntu-24-04
      cloud: gcp
      minCapacity: 0
      maxCapacity: 1
  grants:
    - grant: queue:create-task:highest:proj-bors-ng/ci
      to: repo:github.com/bors-ng/bors-ng:*
