git-cinnabar:
  adminRoles:
    - login-identity:github/1038527|glandium
  repos:
    - github.com/glandium/git-cinnabar:*
  secrets:
    codecov: true
  workerPools:
    linux:
      imageset: generic-worker-ubuntu-24-04
      cloud: gcp
      maxCapacity: 5
      machineType: "zones/{zone}/machineTypes/n2-highmem-4"
      instanceTypes:
        r5.xlarge: 1
    ######################################################################
    # This section can be removed once git-cinnabar uses the new "windows"
    # worker pool below.
    #
    win2012r2:
      imageset: generic-worker-win2022
      cloud: azure
      maxCapacity: 2
      instanceTypes:
        m7i.2xlarge: 1
        m7i.4xlarge: 1
        c7i.2xlarge: 1
        c7i.4xlarge: 1
      vmSizes:
        Standard_F8s_v2: 1
        Standard_F16s_v2: 1
        Standard_D8s_v5: 1
        Standard_D16s_v5: 1
    #
    ######################################################################
    windows:
      imageset: generic-worker-win2022
      cloud: azure
      maxCapacity: 2
      instanceTypes:
        m7i.2xlarge: 1
        m7i.4xlarge: 1
        c7i.2xlarge: 1
        c7i.4xlarge: 1
      vmSizes:
        Standard_F8s_v2: 1
        Standard_F16s_v2: 1
        Standard_D8s_v5: 1
        Standard_D16s_v5: 1
  clients:
    worker-osx:
      scopes:
        - assume:worker-pool:proj-git-cinnabar/osx
        - assume:worker-id:proj-git-cinnabar/travis-*
    worker-macos:
      scopes:
        - assume:worker-pool:proj-git-cinnabar/macos
        - assume:worker-id:proj-git-cinnabar/gha-*
  grants:
    - grant:
        - queue:create-task:highest:proj-git-cinnabar/linux
        ##############################################################
        # The line below can be removed once git-cinnabar uses the new
        # "windows" worker pool
        ##############################################################
        - queue:create-task:highest:proj-git-cinnabar/win2012r2
        - queue:create-task:highest:proj-git-cinnabar/windows
        # these two workerTypes are implemented in Github Actions (!)
        - queue:create-task:highest:proj-git-cinnabar/osx
        - queue:create-task:highest:proj-git-cinnabar/macos
        - queue:scheduler-id:taskcluster-github
      to:
        - repo:github.com/glandium/git-cinnabar:decision-task

    - grant: assume:repo:github.com/glandium/git-cinnabar:decision-task
      to: repo:github.com/glandium/git-cinnabar:pull-request

    - grant:
        - assume:repo:github.com/glandium/git-cinnabar:decision-task
        - secrets:get:project/git-cinnabar/codecov
        - queue:route:index.project.git-cinnabar.*
      to:
        - repo:github.com/glandium/git-cinnabar:release
        - repo:github.com/glandium/git-cinnabar:release:*
        - repo:github.com/glandium/git-cinnabar:branch:*
        - repo:github.com/glandium/git-cinnabar:tag:*
