webrender:
  adminRoles:
    - login-identity:github/27658|jdm
    - login-identity:github/332653|jrmuizel
    - login-identity:github/485789|staktrace
    - login-identity:github/39062770|gw3583
  repos:
    - github.com/servo/webrender:*
    - github.com/staktrace/webrender:*
  workerPools:
    ci-linux:
      owner: kats@mozilla.com
      emailOnError: false
      imageset: generic-worker-ubuntu-24-04
      cloud: aws
      minCapacity: 0
      maxCapacity: 2
  clients:
    macos:
      scopes:
        - assume:worker-pool:proj-webrender/ci-macos
        - assume:worker-id:proj-webrender/*
  grants:
    - grant:
        - queue:create-task:highest:proj-webrender/ci-linux
        - queue:create-task:highest:proj-webrender/ci-macos
        - queue:route:index.project.webrender.ci.*
      to:
        - repo:github.com/servo/webrender:*
        - repo:github.com/staktrace/webrender:*
