---
# This file describes AWS constants used to build worker pools
# It supports two top level dictionaries:
#
# # List all the available subnets in supported regions
# # and their associated availability zone
# subnets:
#   <aws-region-name>:
#     <aws-availability-zone>: <aws-subnet-id>
#
# # List all the available security groups in supported regions
# security_groups:
#   <aws-region-name>:
#     <network-name>: <aws-security-group-id>
#
# Please do not move or edit the structure of that file as
# it's being actively used by the fuzzing team decision task
# to manage worker pools
# If you remove a region, please reach out to fuzzing+taskcluster@mozilla.com

subnets:
  us-west-1:
    us-west-1a: subnet-0e43a99e9c865689e
    us-west-1b: subnet-0a5344f7003aede7c

  us-west-2:
    us-west-2a: subnet-048a61782df5ba378
    us-west-2b: subnet-05053e2898fc744e9
    us-west-2c: subnet-036a0812d241733ef
    us-west-2d: subnet-0fc336d9e5934c913

  us-east-1:
    us-east-1a: subnet-0ab0ba0d9836bb7ab
    us-east-1b: subnet-08c284e43fd180150
    us-east-1c: subnet-0034e6efd82d24939
    us-east-1d: subnet-05a055adc7a81adc0
    us-east-1e: subnet-03bbdcf0ec23f8caa
    us-east-1f: subnet-0cc340c5cf9346dcc

  us-east-2:
    us-east-2a: subnet-05205c91d6a9f06e6
    us-east-2b: subnet-082be4d0d5e7e4d58
    us-east-2c: subnet-01eb0c6a5e15846db

security_groups:
  us-west-1:
    no-inbound: sg-00c4014bc978171d5
    docker-worker: sg-087645ac9907433fb
    rdp: sg-0b6238847123dd200
    ssh: sg-0ede39e4132f5322d

  us-west-2:
    no-inbound: sg-0659c2937ecbe7254
    docker-worker: sg-0823a836c2060fd8d
    rdp: sg-099eed49a07e1bc26
    ssh: sg-0c1d32f2472768325

  us-east-1:
    no-inbound: sg-07f7d21a488e192c6
    docker-worker: sg-01d0551837788c469
    rdp: sg-00d1cffb677ebefc9
    ssh: sg-05a63dba69f8ef87e

  us-east-2:
    no-inbound: sg-00a9d64b3595c5088
    docker-worker: sg-0102bdcf7fc92b3e9
    rdp: sg-0b5c6eacbbbc7dde9
    ssh: sg-046592e27c18b856d
