# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/community-tc-workers/global/images/docker-worker-06zh2jnsaud6lidlb226
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0dec39d7aada81074
      us-east-2: ami-092b8b27bd19354b1
      us-west-1: ami-00a820994ea4f2436
      us-west-2: ami-0c01795c91ab91152
# v44.23.4 docker worker which includes the disableSeccomp feature
docker-worker-legacy:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-community-gcp-googlecompute-2022-12-19t19-01-04z
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0ec6d5fc54628fa9b
      us-east-2: ami-071b3ff08f2d9c1dd
      us-west-1: ami-03f677a21b2fadb15
      us-west-2: ami-0de87470eb34a8e36
generic-worker-freebsd:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/ce90750aa55ab27f6111040925ebe820ec939ff0/imagesets/generic-worker-freebsd/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-03ab357e5bc4fde14
      us-west-2: ami-0aec17d43bf888035
      us-east-1: ami-05904e574e7a66fa8
      us-east-2: ami-090ed2386963df7bf
generic-worker-ubuntu-22-04:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/f72c5a49169eacd0b98b90f6a1a7dcff0c262003/imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-22-04-9ij7tf0o90xfcd8ouplp
  aws:
    amis:
      us-west-1: ami-0ff3397baf95d32f9
      us-west-2: ami-0f452ac6a610198ac
      us-east-1: ami-077991a1338ea43fa
      us-east-2: ami-0640aac4897ddc0c8
generic-worker-ubuntu-24-04:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/c044294fb8be49e0d491077befff5f6a403e218e/imagesets/generic-worker-ubuntu-24-04/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-krmophte1adibczmkvi9
  aws:
    amis:
      us-west-1: ami-03f903faa85bf485d
      us-west-2: ami-0b4a2b6df1a43e255
      us-east-1: ami-0743265d375ee455c
      us-east-2: ami-0e01793fa43769ca5
generic-worker-ubuntu-22-04-arm64:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/48bb7ac15a9f88f6cb987cbbf23935cc139896a1/imagesets/generic-worker-ubuntu-22-04-arm64/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-22-04-arm64-zzo3oq3x3p4cum69tqie
generic-worker-ubuntu-22-04-staging:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: false
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/62d941e85265c200e9f2554eb7eaf8aefe1074b1/imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-0a3db3d32aec25140
      us-west-2: ami-0998d30cd688d2c47
      us-east-1: ami-02fbca49f6f6e2177
      us-east-2: ami-09bcbca24ec070ced
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-22-04-staging-j9vxje88zn6uys9sndjr
generic-worker-win2022:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-01374ec10a89c52ad
      us-west-1: ami-007d11990f836944b
      us-west-2: ami-0cdd0ab692944570b
      us-east-2: ami-07ac9b6b7dd73feba
  azure:
    images:
      centralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-6sw8983x76nbdcppkfmx-centralus
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-6sw8983x76nbdcppkfmx-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-6sw8983x76nbdcppkfmx-eastus2
      northcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-6sw8983x76nbdcppkfmx-northcentralus
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-6sw8983x76nbdcppkfmx-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-6sw8983x76nbdcppkfmx-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-6sw8983x76nbdcppkfmx-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/c65042068184f75b24da23ecda5608a59c44b67d/imagesets/generic-worker-win2022/bootstrap.ps1
generic-worker-win2022-staging:
  workerImplementation: generic-worker
  azure:
    images:
      centralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-2zarf8vv8g6a7oghayny-centralus
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-2zarf8vv8g6a7oghayny-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-2zarf8vv8g6a7oghayny-eastus2
      northcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-2zarf8vv8g6a7oghayny-northcentralus
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-2zarf8vv8g6a7oghayny-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-2zarf8vv8g6a7oghayny-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-2zarf8vv8g6a7oghayny-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/422f0304b5592b23879d0f3c1fe9aeb347410bcd/imagesets/generic-worker-win2022-staging/bootstrap.ps1
generic-worker-win2016-amd:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-2: ami-067ad32351f1896e8
      us-east-1: ami-01a058be87eb2c07a
      us-east-2: ami-099303062350807d9
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: jkratzer@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/6a2bf563af1a44d9187380dbc076571ffc8dc465/imagesets/generic-worker-win2016-amd/bootstrap.ps1
generic-worker-win2022-gpu:
  azure:
    images:
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-smt348aan9qrq5kleez8-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-smt348aan9qrq5kleez8-eastus2
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-smt348aan9qrq5kleez8-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-smt348aan9qrq5kleez8-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-smt348aan9qrq5kleez8-westus2
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        livelogExecutable: C:\generic-worker\livelog.exe
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 15
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/4fbf1e860832cb8576fe27b63eec0d45615c344f/imagesets/generic-worker-win2022-gpu/bootstrap.ps1
