# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/community-tc-workers/global/images/docker-worker-q01vcevv66mebrvhw946
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0c2cd4c7b653e7ef1
      us-east-2: ami-037a373be874160ee
      us-west-1: ami-0c4bf106093c585b7
      us-west-2: ami-089e082f0e627ecfb
# v44.23.4 docker worker which includes the disableSeccomp feature
docker-worker-legacy:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-community-gcp-googlecompute-2022-12-19t19-01-04z
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0ec6d5fc54628fa9b
      us-east-2: ami-071b3ff08f2d9c1dd
      us-west-1: ami-03f677a21b2fadb15
      us-west-2: ami-0de87470eb34a8e36
generic-worker-freebsd:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/ce90750aa55ab27f6111040925ebe820ec939ff0/imagesets/generic-worker-freebsd/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-03ab357e5bc4fde14
      us-west-2: ami-0aec17d43bf888035
      us-east-1: ami-05904e574e7a66fa8
      us-east-2: ami-090ed2386963df7bf
generic-worker-ubuntu-24-04:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/86a6e0a66fe43394377ee1dfc532464e942209fa/imagesets/generic-worker-ubuntu-24-04/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-wum4deiytlsf7jqvxo1p
  aws:
    amis:
      us-west-1: ami-07ad932ad339752e7
      us-west-2: ami-03647e023adc4d12e
      us-east-1: ami-00538871120f652a8
      us-east-2: ami-080f6134366991cdb
generic-worker-ubuntu-24-04-arm64:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/86a6e0a66fe43394377ee1dfc532464e942209fa/imagesets/generic-worker-ubuntu-24-04-arm64/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-arm64-d2pxl65wr678n1qm0n6d
generic-worker-ubuntu-24-04-staging:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/86a6e0a66fe43394377ee1dfc532464e942209fa/imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-0266997b770ede46d
      us-west-2: ami-04eb9170d2e628947
      us-east-1: ami-0d6d1b79e07db1b76
      us-east-2: ami-03b6d9f1f40aab0ff
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-staging-bzfqjpixg3lgvvmhuh68
generic-worker-win2022:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-017d7a126d9c96455
      us-west-1: ami-0c292dd21315b7afe
      us-west-2: ami-09cdd180f325cbec9
      us-east-2: ami-0e7211fa691cb80b7
  azure:
    images:
      centralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-uoj3lyt63q0zmfu3txka-centralus
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-uoj3lyt63q0zmfu3txka-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-uoj3lyt63q0zmfu3txka-eastus2
      northcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-uoj3lyt63q0zmfu3txka-northcentralus
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-uoj3lyt63q0zmfu3txka-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-uoj3lyt63q0zmfu3txka-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-uoj3lyt63q0zmfu3txka-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/5e9c2fba009d6173b13a6d0b8b908042be15b491/imagesets/generic-worker-win2022/bootstrap.ps1
generic-worker-win2022-staging:
  workerImplementation: generic-worker
  azure:
    images:
      centralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-nq7412idao1upt6aozl4-centralus
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-fnedtl6nboqp2ezji4cc-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-fnedtl6nboqp2ezji4cc-eastus2
      northcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-nq7412idao1upt6aozl4-northcentralus
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-fnedtl6nboqp2ezji4cc-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-fnedtl6nboqp2ezji4cc-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-fnedtl6nboqp2ezji4cc-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/672161a7f72212d7ebbbf9834474fb20f56943b2/imagesets/generic-worker-win2022-staging/bootstrap.ps1
generic-worker-win2022-gpu:
  azure:
    images:
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-j9bt5qm7gj3nlhx7ltwl-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-j9bt5qm7gj3nlhx7ltwl-eastus2
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-j9bt5qm7gj3nlhx7ltwl-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-j9bt5qm7gj3nlhx7ltwl-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-j9bt5qm7gj3nlhx7ltwl-westus2
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/d69530d8e93a3de8994592e34f6ca7e50cc680d0/imagesets/generic-worker-win2022-gpu/bootstrap.ps1
generic-worker-win11-24h2-staging:
  workerImplementation: generic-worker
  azure:
    images:
      centralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-49z14erp0a8q2549ixc0-centralus
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-49z14erp0a8q2549ixc0-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-49z14erp0a8q2549ixc0-eastus2
      northcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-49z14erp0a8q2549ixc0-northcentralus
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-49z14erp0a8q2549ixc0-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-49z14erp0a8q2549ixc0-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-49z14erp0a8q2549ixc0-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/ad69b7deb5fbc7e6c9b6b4f9fb7ac8af6c3a6885/imagesets/generic-worker-win11-24h2-staging/bootstrap.ps1
