# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/community-tc-workers/global/images/docker-worker-2nnt9g23nml7bodzi7fn
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-west-1: ami-0b3c75fe5f11b55fb
      us-west-2: ami-0a34b5ff2d90358e6
      us-east-1: ami-036590c4dfaaa0de1
      us-east-2: ami-0f2eacfe80f4a642a
# v44.23.4 docker worker which includes the disableSeccomp feature
docker-worker-legacy:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-community-gcp-googlecompute-2022-12-19t19-01-04z
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0ec6d5fc54628fa9b
      us-east-2: ami-071b3ff08f2d9c1dd
      us-west-1: ami-03f677a21b2fadb15
      us-west-2: ami-0de87470eb34a8e36
generic-worker-freebsd:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/ce90750aa55ab27f6111040925ebe820ec939ff0/imagesets/generic-worker-freebsd/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-03ab357e5bc4fde14
      us-west-2: ami-0aec17d43bf888035
      us-east-1: ami-05904e574e7a66fa8
      us-east-2: ami-090ed2386963df7bf
generic-worker-ubuntu-24-04:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/9a0c6ce5a0ca3eef068d47f96e54343728bbe3cc/imagesets/generic-worker-ubuntu-24-04/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-whqymd1q2muptuxp2nht
  aws:
    amis:
      us-west-1: ami-02b27a24aeb261ec7
      us-west-2: ami-08d98154561fdcda1
      us-east-1: ami-0047fa59d1248409d
      us-east-2: ami-058caf44dee12a0c7
generic-worker-ubuntu-24-04-arm64:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/9a0c6ce5a0ca3eef068d47f96e54343728bbe3cc/imagesets/generic-worker-ubuntu-24-04-arm64/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-arm64-27b39yyucaq9v5utrwqc
generic-worker-ubuntu-24-04-staging:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/9a0c6ce5a0ca3eef068d47f96e54343728bbe3cc/imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-0f6a01bf7dda7f4f6
      us-west-2: ami-0d1138a6548733408
      us-east-1: ami-02233a15a4788cdeb
      us-east-2: ami-000b57e8514f93002
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-staging-y2p88cqe45maiozi0na0
generic-worker-win2022:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-1: ami-0d7bbab1eef03686c
      us-west-2: ami-08bb06faf264bd144
      us-east-1: ami-0acf1ae38c2387285
      us-east-2: ami-055bc18ba30433c29
  azure:
    images:
      centralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-pq0b9ehxpbyvjksa5ip8-centralus
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-pq0b9ehxpbyvjksa5ip8-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-pq0b9ehxpbyvjksa5ip8-eastus2
      northcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-pq0b9ehxpbyvjksa5ip8-northcentralus
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-pq0b9ehxpbyvjksa5ip8-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-pq0b9ehxpbyvjksa5ip8-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-pq0b9ehxpbyvjksa5ip8-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/9a0c6ce5a0ca3eef068d47f96e54343728bbe3cc/imagesets/generic-worker-win2022/bootstrap.ps1
generic-worker-win2022-staging:
  workerImplementation: generic-worker
  azure:
    images:
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-cho2b67efi8no0fgdz65-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-cho2b67efi8no0fgdz65-eastus2
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-cho2b67efi8no0fgdz65-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-cho2b67efi8no0fgdz65-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-cho2b67efi8no0fgdz65-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/03cc8918b6a0646619e888b9f230bc52a2b3e78b/imagesets/generic-worker-win2022-staging/bootstrap.ps1
generic-worker-win2022-gpu:
  azure:
    images:
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-8xw0kt61mx2ch18i9ud0-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-8xw0kt61mx2ch18i9ud0-eastus2
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-8xw0kt61mx2ch18i9ud0-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-8xw0kt61mx2ch18i9ud0-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-8xw0kt61mx2ch18i9ud0-westus2
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/224c735b11ce5d9d982e33c8265f5ce8002f0ddf/imagesets/generic-worker-win2022-gpu/bootstrap.ps1
generic-worker-win11-24h2-staging:
  workerImplementation: generic-worker
  azure:
    images:
      centralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-47gqqi6nymlby91kawhd-centralus
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-47gqqi6nymlby91kawhd-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-47gqqi6nymlby91kawhd-eastus2
      northcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-47gqqi6nymlby91kawhd-northcentralus
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-47gqqi6nymlby91kawhd-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-47gqqi6nymlby91kawhd-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-47gqqi6nymlby91kawhd-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/7085982e5a891994bf3289694365e301e1a5554c/imagesets/generic-worker-win11-24h2-staging/bootstrap.ps1
