# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)
docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/community-tc-workers/global/images/docker-worker-sfwv7ea5qm9wuoig3274
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-west-1: ami-02bd313d7bdc30ca2
      us-west-2: ami-0c2f7ba5e98be094a
      us-east-1: ami-00200edd7c6e8e836
      us-east-2: ami-0a4917cc81d805e72
# v44.23.4 docker worker which includes the disableSeccomp feature
docker-worker-legacy:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-community-gcp-googlecompute-2022-12-19t19-01-04z
  aws:
    # originally built with the `docker_community_aws` builder in monopacker
    amis:
      us-east-1: ami-0ec6d5fc54628fa9b
      us-east-2: ami-071b3ff08f2d9c1dd
      us-west-1: ami-03f677a21b2fadb15
      us-west-2: ami-0de87470eb34a8e36
generic-worker-freebsd:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        enableInteractive: true
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://github.com/taskcluster/community-tc-config/blob/ce90750aa55ab27f6111040925ebe820ec939ff0/imagesets/generic-worker-freebsd/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-03ab357e5bc4fde14
      us-west-2: ami-0aec17d43bf888035
      us-east-1: ami-05904e574e7a66fa8
      us-east-2: ami-090ed2386963df7bf
generic-worker-ubuntu-24-04:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        d2gConfig:
          enableD2G: true
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        enableInteractive: true
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/a7feb1fa06a2edc9ca15af772303b25947dd6a1e/imagesets/generic-worker-ubuntu-24-04/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-wv1hlz2rvkjjggfizsl0
  aws:
    amis:
      us-west-1: ami-0df43db5d2cd74d8d
      us-west-2: ami-0d38c0d20175ea8a9
      us-east-1: ami-05d4f3bacb496077d
      us-east-2: ami-090a5dfd7b93f705b
generic-worker-ubuntu-24-04-arm64:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        d2gConfig:
          enableD2G: true
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        enableInteractive: true
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/a7feb1fa06a2edc9ca15af772303b25947dd6a1e/imagesets/generic-worker-ubuntu-24-04-arm64/bootstrap.sh
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-arm64-l578xrm91rt42hwtgsdm
generic-worker-ubuntu-24-04-staging:
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        d2gConfig:
          enableD2G: true
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        enableInteractive: true
        idleTimeoutSecs: 15
        shutdownMachineOnIdle: true
        workerTypeMetadata:
          machine-setup:
            maintainer: taskcluster-notifications+workers@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/e27dfe930167444a3910e9506bd95cd7428104f2/imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
  aws:
    amis:
      us-west-1: ami-04b6bd92cca2d27e7
      us-west-2: ami-0b37bf14faf4ccb84
      us-east-1: ami-05aeba31c6fc212ea
      us-east-2: ami-005b65700d676f6c2
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-ubuntu-24-04-staging-e1qv41jhx97cjk62js0c
generic-worker-win2022:
  workerImplementation: generic-worker
  aws:
    amis:
      us-west-1: ami-0d7bbab1eef03686c
      us-west-2: ami-08bb06faf264bd144
      us-east-1: ami-0acf1ae38c2387285
      us-east-2: ami-055bc18ba30433c29
  azure:
    images:
      centralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-mamr9lrd9j59b743fz4f-centralus
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-mamr9lrd9j59b743fz4f-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-mamr9lrd9j59b743fz4f-eastus2
      northcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-mamr9lrd9j59b743fz4f-northcentralus
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-mamr9lrd9j59b743fz4f-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-mamr9lrd9j59b743fz4f-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-mamr9lrd9j59b743fz4f-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/d5b59b661ff6611a961279f13797cbc1b87e34cf/imagesets/generic-worker-win2022/bootstrap.ps1
generic-worker-win2022-staging:
  workerImplementation: generic-worker
  azure:
    images:
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-232snl61rwiu9tzr9t8a-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-232snl61rwiu9tzr9t8a-eastus2
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-232snl61rwiu9tzr9t8a-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-232snl61rwiu9tzr9t8a-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-232snl61rwiu9tzr9t8a-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/e29f2aa12e8518e8b39cd9577233130a4c15bcf2/imagesets/generic-worker-win2022-staging/bootstrap.ps1
generic-worker-win2022-gpu:
  azure:
    images:
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-nrqayppc5zqhdz4x3wxl-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-nrqayppc5zqhdz4x3wxl-eastus2
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-nrqayppc5zqhdz4x3wxl-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-nrqayppc5zqhdz4x3wxl-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-nrqayppc5zqhdz4x3wxl-westus2
  workerImplementation: generic-worker
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        shutdownMachineOnInternalError: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/d5b59b661ff6611a961279f13797cbc1b87e34cf/imagesets/generic-worker-win2022-gpu/bootstrap.ps1
generic-worker-win11-24h2-staging:
  workerImplementation: generic-worker
  azure:
    images:
      centralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-y1ufoyvji0o9hjn26e6d-centralus
      eastus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-y1ufoyvji0o9hjn26e6d-eastus
      eastus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-y1ufoyvji0o9hjn26e6d-eastus2
      northcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-y1ufoyvji0o9hjn26e6d-northcentralus
      southcentralus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-y1ufoyvji0o9hjn26e6d-southcentralus
      westus: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-y1ufoyvji0o9hjn26e6d-westus
      westus2: /subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-y1ufoyvji0o9hjn26e6d-westus2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        idleTimeoutSecs: 15
        livelogExecutable: C:\generic-worker\livelog.exe
        shutdownMachineOnIdle: true
        taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/community-tc-config/b68c2d5b07909a749a958a665c3c9db92fe819b0/imagesets/generic-worker-win11-24h2-staging/bootstrap.ps1
